### ISSUE TITLE
Plugin not working on 1.19.3

### ISSUE THREAD

**Issue by SirvydasS** [BONNePlayground/DragonFights#10]
#### Describe the bug

Plugin not loading correctly on server startup

#### Steps to reproduce the behavior

Use 1.19.3 and this plugin.

#### Expected behavior

Plugin working.

#### Screenshots and videos (Optional)

`[10:00:46] [Server thread/ERROR]: [BentoBox] Skipping DragonFights due to an unhandled exception...
[10:00:46] [Server thread/ERROR]: [BentoBox] java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because the return value of "java.util.Map.get(Object)" is null
	at DragonFights-1.4.3.jar//lv.id.bonne.dragonfights.entity.CustomEntityAPI.getAPI(CustomEntityAPI.java:35)
	at DragonFights-1.4.3.jar//lv.id.bonne.dragonfights.DragonFightsAddon.onLoad(DragonFightsAddon.java:42)
	at BentoBox-1.22.0-SNAPSHOT-b2306.jar//world.bentobox.bentobox.managers.AddonsManager.initializeAddon(AddonsManager.java:226)
	at BentoBox-1.22.0-SNAPSHOT-b2306.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:199)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at BentoBox-1.22.0-SNAPSHOT-b2306.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:142)
	at BentoBox-1.22.0-SNAPSHOT-b2306.jar//world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:166)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:372)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:550)
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugin(CraftServer.java:624)
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.enablePlugins(CraftServer.java:538)
	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:310)
	at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1117)
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321)
	at java.base/java.lang.Thread.run(Thread.java:833)`

##### BentoBox Version (Mandatory)

```
[10:04:14 INFO]: Running PURPUR Netinkama.
[10:04:14 INFO]: BentoBox versija: 1.22.0-SNAPSHOT-b2306
[10:04:14 INFO]: Database: MARIADB
[10:04:14 INFO]: Loaded Game Worlds:
[10:04:14 INFO]: oneblock_world (OneBlock): Paviršiaus pasaulis, Neteris, Pabaiga
[10:04:14 INFO]: Loaded Addons:
[10:04:14 INFO]: AOneBlock 1.12.0-SNAPSHOT-b279 (ENABLED)
[10:04:14 INFO]: Bank 1.4.0-SNAPSHOT-b62 (ENABLED)
[10:04:14 INFO]: Biomes 2.1.0-SNAPSHOT-b238 (ENABLED)
[10:04:14 INFO]: Border 4.0.0-SNAPSHOT-b145 (ENABLED)
[10:04:14 INFO]: Challenges 1.1.0-SNAPSHOT-b494 (ENABLED)
[10:04:14 INFO]: DimensionalTrees 1.6.1-SNAPSHOT-b84 (ENABLED)
[10:04:14 INFO]: DragonFights 1.4.3 (ERROR)
[10:04:14 INFO]: ExtraMobs 1.12 (ENABLED)
[10:04:14 INFO]: Greenhouses 1.7.0-SNAPSHOT-b324 (ENABLED)
[10:04:14 INFO]: Level 2.9.1-SNAPSHOT-b511 (ENABLED)
[10:04:14 INFO]: Likes 2.4.0-SNAPSHOT-b90 (ENABLED)
[10:04:14 INFO]: Limits 1.19.1-SNAPSHOT-b301 (ENABLED)
[10:04:14 INFO]: MagicCobblestoneGenerator 2.5.0-SNAPSHOT-b252 (ENABLED)
[10:04:14 INFO]: TwerkingForTrees 1.4.4-SNAPSHOT-b60 (ENABLED)
[10:04:14 INFO]: Warps 1.13.0-SNAPSHOT-b329 (ENABLED)
```

**Comment by BONNe** [comment]
I am very sorry, I forgot to publish the release. (being sick does not help with memory).

**Comment by SirvydasS** [comment]
When trying to spawn Dragon, it creates all towers correctly but when come turn to spawn dragon it starts to spam a lot errors and dragon didn't show up:

`[14:21:58] [Server thread/WARN]: [BentoBox] Task #11985 for BentoBox v1.22.0-SNAPSHOT-b2306 generated an exception
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at lv.id.bonne.dragonfights.v1_19_R2.NMSEntityRegistry.lambda$applyRegister$0(NMSEntityRegistry.java:138) ~[DragonFights-1.4.4.jar:?]
	at net.minecraft.world.entity.EntityType.create(EntityType.java:590) ~[?:?]
	at lv.id.bonne.dragonfights.v1_19_R2.battle.BentoBoxDragonBattle.lambda$createNewDragon$8(BentoBoxDragonBattle.java:1317) ~[DragonFights-1.4.4.jar:?]
	at java.util.Optional.map(Optional.java:260) ~[?:?]
	at lv.id.bonne.dragonfights.v1_19_R2.battle.BentoBoxDragonBattle.createNewDragon(BentoBoxDragonBattle.java:1317) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R2.battle.BentoBoxDragonBattle.findOrCreateDragon(BentoBoxDragonBattle.java:1277) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R2.battle.BentoBoxDragonBattle.tickBattle(BentoBoxDragonBattle.java:417) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:468) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:416) ~[DragonFights-1.4.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at org.bukkit.craftbukkit.v1_19_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:482) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1876]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.reflect.InvocationTargetException
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at lv.id.bonne.dragonfights.v1_19_R2.NMSEntityRegistry.lambda$applyRegister$0(NMSEntityRegistry.java:134) ~[DragonFights-1.4.4.jar:?]
	... 16 more
Caused by: java.lang.NoSuchMethodError: net.minecraft.world.level.pathfinder.PathEntity: method 'void <init>()' not found
	at lv.id.bonne.dragonfights.v1_19_R2.entity.BentoBoxEnderDragon.<init>(BentoBoxEnderDragon.java:68) ~[DragonFights-1.4.4.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at lv.id.bonne.dragonfights.v1_19_R2.NMSEntityRegistry.lambda$applyRegister$0(NMSEntityRegistry.java:134) ~[DragonFights-1.4.4.jar:?]
	... 16 more`

**Comment by BONNe** [comment]
I am very sorry again.

I uploaded the wrong jar version. Please try to download 1.4.4 version again.
