### ISSUE TITLE
Errors spam when a player enter the end

### ISSUE THREAD

**Issue by Olthoo** [BONNePlayground/DragonFights#14]
#### Describe the bug
Don't know the exact cause yet but if a player enter the end with hostile mob spawning off it will start the loop of error and not spawn the dragon,
It also happend when a player is killing a dragon sometimes..

#### Steps to reproduce the behavior
Enter the end with hostile mob spawning off

#### Expected behavior
spawn the dragon anyway or tell the player that he need to allow mob spawning

#### Screenshots and videos (Optional)
Logs of the error, I can send full logs if needed
```
[09:50:31] [Server thread/WARN]: [BentoBox] Task #1942129 for BentoBox v1.21.1 generated an exception
java.lang.ClassCastException: class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon cannot be cast to class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon (lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @22c644fc; lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @17cf7d61)
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.createNewDragon(BentoBoxDragonBattle.java:1316) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.findOrCreateDragon(BentoBoxDragonBattle.java:1272) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.tickBattle(BentoBoxDragonBattle.java:417) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:468) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:416) ~[DragonFights-1.4.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:50:31] [Server thread/WARN]: [BentoBox] Task #1942129 for BentoBox v1.21.1 generated an exception
java.lang.ClassCastException: class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon cannot be cast to class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon (lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @22c644fc; lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @17cf7d61)
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.createNewDragon(BentoBoxDragonBattle.java:1316) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.findOrCreateDragon(BentoBoxDragonBattle.java:1272) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.tickBattle(BentoBoxDragonBattle.java:417) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:468) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:416) ~[DragonFights-1.4.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:50:31] [Server thread/WARN]: [BentoBox] Task #1942129 for BentoBox v1.21.1 generated an exception
java.lang.ClassCastException: class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon cannot be cast to class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon (lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @22c644fc; lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @17cf7d61)
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.createNewDragon(BentoBoxDragonBattle.java:1316) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.findOrCreateDragon(BentoBoxDragonBattle.java:1272) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.tickBattle(BentoBoxDragonBattle.java:417) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:468) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:416) ~[DragonFights-1.4.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:50:31] [Server thread/WARN]: [BentoBox] Task #1942129 for BentoBox v1.21.1 generated an exception
java.lang.ClassCastException: class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon cannot be cast to class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon (lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @22c644fc; lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @17cf7d61)
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.createNewDragon(BentoBoxDragonBattle.java:1316) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.findOrCreateDragon(BentoBoxDragonBattle.java:1272) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.tickBattle(BentoBoxDragonBattle.java:417) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:468) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:416) ~[DragonFights-1.4.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:50:31] [Server thread/WARN]: [BentoBox] Task #1942129 for BentoBox v1.21.1 generated an exception
java.lang.ClassCastException: class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon cannot be cast to class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon (lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @22c644fc; lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @17cf7d61)
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.createNewDragon(BentoBoxDragonBattle.java:1316) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.findOrCreateDragon(BentoBoxDragonBattle.java:1272) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.tickBattle(BentoBoxDragonBattle.java:417) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:468) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:416) ~[DragonFights-1.4.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:50:31] [Server thread/WARN]: [BentoBox] Task #1942129 for BentoBox v1.21.1 generated an exception
java.lang.ClassCastException: class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon cannot be cast to class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon (lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @22c644fc; lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @17cf7d61)
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.createNewDragon(BentoBoxDragonBattle.java:1316) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.findOrCreateDragon(BentoBoxDragonBattle.java:1272) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.tickBattle(BentoBoxDragonBattle.java:417) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:468) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:416) ~[DragonFights-1.4.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[09:50:31] [Server thread/WARN]: [BentoBox] Task #1942129 for BentoBox v1.21.1 generated an exception
java.lang.ClassCastException: class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon cannot be cast to class lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon (lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @22c644fc; lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @17cf7d61)
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.createNewDragon(BentoBoxDragonBattle.java:1316) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.findOrCreateDragon(BentoBoxDragonBattle.java:1272) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.v1_19_R1.battle.BentoBoxDragonBattle.tickBattle(BentoBoxDragonBattle.java:417) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:468) ~[DragonFights-1.4.4.jar:?]
	at lv.id.bonne.dragonfights.managers.DragonFightManager$BattleTick.accept(DragonFightManager.java:416) ~[DragonFights-1.4.4.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1500) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:486) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1194) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:310) ~[purpur-1.19.2.jar:git-Purpur-1858]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]```


### Environment

##### BentoBox Version (Mandatory)
<!-- /!\ Leaving this section blank will result in your ticket being closed without further explanation. -->
<!-- Paste the output of `/bentobox version` in the code block below (replace the underscores). Do not provide an image. -->
```[10:16:18 INFO]: Serveur PURPUR 1.19.2.
[10:16:18 INFO]: Version de BentoBox : 1.21.1
[10:16:18 INFO]: Base de données : JSON
[10:16:18 INFO]: Mondes de jeu chargés :
[10:16:18 INFO]: bskyblock_world (BSkyBlock) : Overworld, Nether, End
[10:16:18 INFO]: Addons chargés :
[10:16:18 INFO]: Biomes 2.0.0 (ENABLED)
[10:16:18 INFO]: Border 4.1.0-SNAPSHOT-b149 (ENABLED)
[10:16:18 INFO]: BSkyBlock 1.16.0 (ENABLED)
[10:16:18 INFO]: Chat 1.1.4 (ENABLED)
[10:16:18 INFO]: DragonFights 1.4.4 (ENABLED)
[10:16:18 INFO]: ExtraMobs 1.12 (ENABLED)
[10:16:18 INFO]: Level 2.10.0-SNAPSHOT-b516 (ENABLED)
[10:16:18 INFO]: TwerkingForTrees 1.4.3 (ENABLED)
[10:16:18 INFO]: Warps 1.12.0 (ENABLED)
_______
```

#### Plugins (Optional)

```
_______
```

**Comment by BONNe** [comment]
It looks like you have reloaded BentoBox or server plugins.

Entities does not support reloading, as that is how minecraft works. I would not recommend to ever use reload command as it always creates issues. Just restart.

This is the line that says it was reloaded:

`(lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @22c644fc; lv.id.bonne.dragonfights.v1_19_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.4.4.jar' @17cf7d61)`

You can see that `DragonFights-1.4.4.jar` is the same in both situations, but the hash code that follows @ is different.

**Comment by Olthoo** [comment]
ho my bad, I indeed forgot to restart after a few tweaks..
Thanks for helping!
