### ISSUE TITLE
Could not load plugin 'DragonFights-1.6.0.jar' 

### ISSUE THREAD

**Issue by 4goten** [BONNePlayground/DragonFights#22]
#### Describe the bug
cant load

#### Steps to reproduce the behavior
put DragonFights1.6 into bentobox/addon and start the server

#### Expected behavior
have dragon

#### Screenshots and videos (Optional)
[22:39:14 ERROR]: [ModernPluginLoadingStrategy] Could not load plugin 'DragonFights-1.6.0.jar' in folder 'plugins\BentoBox\addons'
java.lang.IllegalStateException: Provider SpigotPluginProvider{path=plugins\BentoBox\addons\DragonFights-1.6.0.jar, description=org.bukkit.plugin.PluginDescriptionFile@2b8a32d4, jarFile=java.util.jar.JarFile@1a028aca, status=null, dependencyContext=null} attempted to add duplicate plugin identifier Pladdon v1.0 THIS WILL CREATE BUGS!!!
        at io.papermc.paper.plugin.storage.ServerPluginProviderStorage$1.applyContext(ServerPluginProviderStorage.java:28) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.entrypoint.strategy.modern.ModernPluginLoadingStrategy.loadProviders(ModernPluginLoadingStrategy.java:113) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.storage.SimpleProviderStorage.enter(SimpleProviderStorage.java:39) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.manager.SingularRuntimePluginProviderStorage.enter(SingularRuntimePluginProviderStorage.java:57) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.manager.RuntimePluginEntrypointHandler.enter(RuntimePluginEntrypointHandler.java:40) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.loadPlugin(PaperPluginInstanceManager.java:118) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.loadPlugin(PaperPluginManagerImpl.java:82) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:406) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at world.bentobox.bentobox.managers.AddonsManager.loadPladdon(AddonsManager.java:193) ~[BentoBox-1.23.3-SNAPSHOT-b2390.jar:?]
        at world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:173) ~[BentoBox-1.23.3-SNAPSHOT-b2390.jar:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183) ~[?:?]
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) ~[?:?]
        at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992) ~[?:?]
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[?:?]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[?:?]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[?:?]
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[?:?]
        at world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:147) ~[BentoBox-1.23.3-SNAPSHOT-b2390.jar:?]
        at world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:166) ~[BentoBox-1.23.3-SNAPSHOT-b2390.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.19.4.jar:git-Paper-538]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:556) ~[paper-1.19.4.jar:git-Paper-538]
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:467) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:274) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1104) ~[paper-1.19.4.jar:git-Paper-538]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320) ~[paper-1.19.4.jar:git-Paper-538]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[22:39:14 INFO]: [CustomEntityAPI] Loading version v1_19_R3
[22:39:14 ERROR]: [BentoBox] Skipping DragonFights due to an unhandled exception...
[22:39:14 ERROR]: [BentoBox] java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because the return value of "java.util.Map.get(Object)" is null
        at DragonFights-1.4.4.jar//lv.id.bonne.dragonfights.entity.CustomEntityAPI.getAPI(CustomEntityAPI.java:35)
        at DragonFights-1.4.4.jar//lv.id.bonne.dragonfights.DragonFightsAddon.onLoad(DragonFightsAddon.java:42)
        at BentoBox-1.23.3-SNAPSHOT-b2390.jar//world.bentobox.bentobox.managers.AddonsManager.initializeAddon(AddonsManager.java:238)
        at BentoBox-1.23.3-SNAPSHOT-b2390.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:186)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:992)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at BentoBox-1.23.3-SNAPSHOT-b2390.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:147)
        at BentoBox-1.23.3-SNAPSHOT-b2390.jar//world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:166)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281)
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507)
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugin(CraftServer.java:556)
        at org.bukkit.craftbukkit.v1_19_R3.CraftServer.enablePlugins(CraftServer.java:467)
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:274)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:1104)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:320)
        at java.base/java.lang.Thread.run(Thread.java:833)

##### BentoBox Version (Mandatory)
[22:54:07 INFO]: 服务器： PAPER 1.19.4
[22:54:07 INFO]: BentoBox 版本： 1.23.3-SNAPSHOT-b2390
[22:54:07 INFO]: 数据库： JSON
[22:54:07 INFO]: 已载入的游戏世界：
[22:54:07 INFO]: bskyblock_world (BSkyBlock) : 主世界, 下界, 末地
[22:54:07 INFO]: 已载入的附加组件：
[22:54:07 INFO]: Bank 1.5.0 (ENABLED)
[22:54:07 INFO]: Biomes 2.1.1 (ENABLED)
[22:54:07 INFO]: Border 4.1.1 (ENABLED)
[22:54:07 INFO]: BSkyBlock 1.16.1 (ENABLED)
[22:54:07 INFO]: Challenges 1.2.0 (ENABLED)
[22:54:07 INFO]: Chat 1.1.4 (ENABLED)
[22:54:07 INFO]: ControlPanel 1.13.0 (ENABLED)
[22:54:07 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[22:54:07 INFO]: DragonFights 1.6.0 (ERROR)
[22:54:07 INFO]: Level 2.10.0 (ENABLED)
[22:54:07 INFO]: Likes 2.3.1 (ENABLED)
[22:54:07 INFO]: Limits 1.19.1 (ENABLED)
[22:54:07 INFO]: MagicCobblestoneGenerator 2.5.1 (ENABLED)
[22:54:07 INFO]: Visit 1.6.0 (ENABLED)
[22:54:07 INFO]: Warps 1.13.0 (ENABLED)
>
_______
```

#### Plugins (Optional)
<!-- Please paste the `/plugins` output inside the code block below (remove the underscores). Do not provide an image. -->
```
_______
```
 
### Additional context (Optional)
<!-- Any additional information you'd like to provide us. -->
<!-- Please type below this line. -->

**Comment by BONNe** [comment]
Does this version works:
https://ci.codemc.io/job/BONNePlayground/job/DragonFights/
