### ISSUE TITLE
Issue with spawning the dragon

### ISSUE THREAD

**Issue by ItsLeon15** [BONNePlayground/DragonFights#24]
#### Describe the bug

There is an issue where the enderdragon doesn't spawn, I'm using BentoBox V1.17.3 on 1.2.0. 

#### Steps to reproduce the behavior

N/A

#### Expected behavior

The dragon should spawn

##### BentoBox Version (Mandatory)

```
1.17.3
```

#### Plugins (Optional)

```
_______
```
 
### Additional context (Optional)

[14:07:08 WARN]: [BentoBox] Task #8476 for BentoBox v1.17.3 generated an exception
java.lang.ClassCastException: class lv.id.bonne.dragonfights.v1_17_R1.entity.BentoBoxEnderDragon cannot be cast to class lv.id.bonne.dragonfights.v1_17_R1.entity.BentoBoxEnderDragon (lv.id.bonne.dragonfights.v1_17_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.2.0.jar' @4898d0de; lv.id.bonne.dragonfights.v1_17_R1.entity.BentoBoxEnderDragon is in unnamed module of loader 'DragonFights-1.2.0.jar' @5e6e9a5)
        at lv.id.bonne.dragonfights.v1_17_R1.battle.BentoBoxDragonBattle.createNewDragon(BentoBoxDragonBattle.java:1235) ~[DragonFights-1.2.0.jar:?]
        at lv.id.bonne.dragonfights.v1_17_R1.battle.BentoBoxDragonBattle.findOrCreateDragon(BentoBoxDragonBattle.java:1191) ~[DragonFights-1.2.0.jar:?]
        at lv.id.bonne.dragonfights.v1_17_R1.battle.BentoBoxDragonBattle.tickBattle(BentoBoxDragonBattle.java:371) ~[DragonFights-1.2.0.jar:?]
        at lv.id.bonne.dragonfights.managers.DragonFightManager.lambda$startBattleTask$5(DragonFightManager.java:372) ~[DragonFights-1.2.0.jar:?]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:103) ~[patched_1.17.1.jar:git-Paper-402]
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[patched_1.17.1.jar:git-Paper-402]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1567) ~[patched_1.17.1.jar:git-Paper-402]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:490) ~[patched_1.17.1.jar:git-Paper-402]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[patched_1.17.1.jar:git-Paper-402]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1282) ~[patched_1.17.1.jar:git-Paper-402]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-402]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by BONNe** [comment]
Can you share output of `/bentobox version` command as it is required in template?

**Comment by ItsLeon15** [comment]
```
[15:27:23 INFO]: Running PAPER 1.17.1.
[15:27:23 INFO]: BentoBox version: 1.17.3
[15:27:23 INFO]: Database: JSON
[15:27:23 INFO]: Loaded Game Worlds:
[15:27:23 INFO]: islands (islands): Overworld, Nether, The End
[15:27:23 INFO]: Loaded Addons:
[15:27:23 INFO]: AcidIsland 1.18.0 (INCOMPATIBLE)
[15:27:23 INFO]: Biomes 1.14.0 (ENABLED)
[15:27:23 INFO]: Border 3.2.0 (ENABLED)
[15:27:23 INFO]: BSkyBlock 1.15.2 (ENABLED)
[15:27:23 INFO]: Challenges 0.8.4 (ENABLED)
[15:27:23 INFO]: Chat 1.1.4 (ENABLED)
[15:27:23 INFO]: DimensionalTrees 1.6.0 (ENABLED)
[15:27:23 INFO]: DragonFights 1.2.0 (ENABLED)
[15:27:23 INFO]: Level 2.7.2 (ENABLED)
[15:27:23 INFO]: Limits 1.17.2 (ENABLED)
[15:27:23 INFO]: TwerkingForTrees 1.4.3 (ENABLED)
[15:27:23 INFO]: Warps 1.11.1 (ENABLED)```

**Comment by BONNe** [comment]
https://github.com/BONNePlayground/DragonFights/releases/tag/1.3.0
