### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by Olthoo** [BONNePlayground/DragonFights#33]
#### Describe the bug

The addon doesn't work on 1.21 

`[01:06:07 ERROR]: [BentoBox] Skipping DragonFights due to an unhandled exception...
[01:06:07 ERROR]: [BentoBox] java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at DragonFights-1721488638103.jar//io.github.iltotore.customentity.util.ServerVersion.fromServer(ServerVersion.java:59)
        at DragonFights-1721488638103.jar//lv.id.bonne.dragonfights.entity.CustomEntityAPI.getAPI(CustomEntityAPI.java:33)
        at DragonFights-1721488638103.jar//lv.id.bonne.dragonfights.DragonFightsAddon.onLoad(DragonFightsAddon.java:43)
        at BentoBox.jar//world.bentobox.bentobox.managers.AddonsManager.initializeAddon(AddonsManager.java:254)
        at BentoBox.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddon(AddonsManager.java:191)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179) 
        at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:1024)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at BentoBox.jar//world.bentobox.bentobox.managers.AddonsManager.loadAddons(AddonsManager.java:150)
        at BentoBox.jar//world.bentobox.bentobox.BentoBox.onEnable(BentoBox.java:174)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:288)
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:202)
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:109)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:520)
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:654)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:603)
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:327) 
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1229)
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333)
        at java.base/java.lang.Thread.run(Thread.java:1583)`

#### Steps to reproduce the behavior
have a server on 1.21
try to use the addon

#### Expected behavior

The addon is working 

##### BentoBox Version (Mandatory)

```
here is full log with /version and /pl https://mclo.gs/OfAQW6K
_______
```

#### Plugins (Optional)

```
_______
```

**Comment by SirvydasS** [comment]
Having same problem

**Comment by BONNe** [comment]
DragonFight addon added a new entity in Minecraft with name: BentoBox_Ender_Dragon.
Unfortunately, 1.21 changed things and locked down their old entry point. I have not figured out how to add this entity to the game yet.  

Sorry.

**Comment by SirvydasS** [comment]
Can we still expect it to be fixed?

**Comment by SirvydasS** [comment]
any updates?

**Comment by dentatar** [comment]
I’m interested as well!

**Comment by Olthoo** [comment]
Still needed ! 😄

**Comment by peroxide486** [comment]
We need it

**Comment by dermo529** [comment]
Also interested!
